type Project = {
  title: string,
  description: string,
  imageSrc: string,
  imageAlt: string,
  projectLink: string,
}

export const projects: Project[] = [
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
  {
    title: 'Color Sorter',
    description: 'basic project made using Javascript css and html',
    imageSrc: 'caminho/da/imagem',
    imageAlt: 'Color Sorter',
    projectLink: 'https://github.com/Luyz-Castelo/Color-Sorter',
  },
];
